[package]
entrypoint = "src/lib.typ"
name = "tud-letter"
version = "0.1.0"
compiler = "0.13.0"
authors = ["Hugo Ledoux <@hugoledoux>"]
repository = "https://github.com/hugoledoux/tudletter"
description = "A Typst template that (almost?) replicates the TUDelft letter"
keywords = ["TU Delft", "letter"]
license = "MIT"
categories = ["office"]

[template]
path = "template"
entrypoint = "letter.typ"
thumbnail = "thumbnail.png"
